language: c++

cache: apt

dist: trusty

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freeglut; fi

script:
  - make

addons:
  apt:
    packages:
        - freeglut3-dev
        - libxi-dev
        - libxmu-dev
